# Generated by Django 4.2 on 2023-08-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Direccion', models.CharField(max_length=30)),
                ('Tipo', models.CharField(max_length=30)),
                ('NCatastral', models.CharField(max_length=30)),
                ('NMatricula', models.CharField(max_length=30)),
                ('IDpropietario', models.CharField(max_length=30)),
                ('Precio', models.IntegerField()),
                ('Dimencion', models.IntegerField()),
            ],
        ),
    ]
