# Generated by Django 4.2 on 2023-08-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreP', models.CharField(max_length=30)),
                ('NombreS', models.CharField(max_length=30)),
                ('ApellidoP', models.CharField(max_length=30)),
                ('ApellidoS', models.CharField(max_length=30)),
                ('Documento', models.CharField(max_length=30)),
                ('NumeroDocumento', models.IntegerField()),
            ],
        ),
    ]
